apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai-30-project
  namespace: argocd
spec:
  description: "Dedicated project for AI-30 microservices"
  # Only allow manifests from your specific repo
  sourceRepos:
    - 'https://github.com/your-org/ai-30-repo.git'
    