apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-3-0-ods-operator
  namespace: openshift-gitops
  finalizers:
    - argoproj.io/resources-finalizer # Ensures clean deletion of all components
spec:
  project: default
  source:
    repoURL: 'https://github.com/wrenkredhat2/raw_install_ai_30_gpu.git' # Replace with your repo
    targetRevision: main
    path: AI30-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redhat-ods-operator
  syncPolicy:
    automated:
      prune: true      # Automatically removes resources deleted from Git
      selfHeal: true   # Automatically fixes "manual" changes made in the cluster
    syncOptions:
#     - CreateNamespace=true           # Creates namespaces like redhat-ods-operator
      - ServerSideApply=true           # CRITICAL: Handles the large RHOAI/Mesh CRD schemas
      - SkipDryRunOnMissingResource=true # CRITICAL: Allows Wave 5 to proceed while Wave 0 is still installing CRDs
      - RespectIgnoreDifferences=true  # Prevents ArgoCD from fighting with OCP controllers
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m